-- ================================================================
-- THIAGO'S LICORES & SNACKS - Complete Relational Database Setup Script
-- Matching the Relational Schema ERD Image
-- Run this in Supabase Dashboard > SQL Editor
-- (To reset tables, you can run: drop table if exists products, orders, order_items, customers, inventory_movements, promotions cascade;)
-- ================================================================

-- Enable UUID extension if needed
create extension if not exists "uuid-ossp";

-- 1. CUSTOMERS TABLE
create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  first_name varchar(100) not null,
  last_name varchar(100) not null,
  document_number varchar(50),
  phone varchar(30),
  email varchar(100),
  address text,
  city varchar(100),
  created_at timestamptz not null default now()
);

-- 2. PRODUCTS TABLE
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  category varchar(100) not null,
  subcategory varchar(100),
  type varchar(100), -- Added for React Native compatibility
  brand varchar(100),
  description text,
  price integer not null default 0,
  stock integer not null default 0,
  image_url text,
  featured boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Auto-update updated_at on modification
create or replace function update_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create or replace trigger products_updated_at
  before update on public.products
  for each row execute function update_updated_at();

-- 3. ORDERS TABLE
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_id bigint references public.customers(id),
  subtotal integer not null default 0,
  discount_amount integer not null default 0,
  tax_amount integer not null default 0,
  total integer not null default 0,
  promo_code varchar(50),
  payment_method varchar(50) default 'Efectivo',
  status varchar(50) default 'Completado',
  created_at timestamptz not null default now()
);

-- 4. ORDER_ITEMS TABLE
create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade,
  product_id bigint references public.products(id),
  quantity integer not null,
  unit_price integer not null,
  subtotal integer not null
);

-- 5. CARTS TABLE
create table if not exists public.carts (
  id bigint generated by default as identity primary key,
  customer_id bigint references public.customers(id),
  status varchar(50) default 'Activo',
  created_at timestamptz not null default now()
);

-- 6. CART_ITEMS TABLE
create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  cart_id bigint references public.carts(id) on delete cascade,
  product_id bigint references public.products(id),
  quantity integer not null,
  unit_price integer not null,
  subtotal integer not null
);

-- 7. PROMOTIONS TABLE
create table if not exists public.promotions (
  id bigint generated by default as identity primary key,
  code varchar(50) unique not null,
  description text,
  discount_percent real not null,
  start_date date,
  end_date date,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- 8. USERS TABLE
create table if not exists public.users (
  id text primary key,
  full_name varchar(255) not null,
  email varchar(255) unique not null,
  password_hash text not null,
  role varchar(50) default 'Vendedor',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- 9. SETTINGS TABLE
create table if not exists public.settings (
  id bigint generated by default as identity primary key,
  store_name varchar(255) not null,
  phone varchar(30),
  email varchar(100),
  address text,
  logo_url text,
  tax_percentage numeric(5,2) not null default 0.00
);

-- 10. INVENTORY_MOVEMENTS TABLE
create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete cascade,
  movement_type varchar(50) not null, -- 'ENTRADA', 'SALIDA', 'AJUSTE', 'VENTA'
  quantity integer not null,
  previous_stock integer not null,
  now_stock integer not null,
  notes text,
  created_at timestamptz not null default now()
);

-- 11. SUPPLIERS TABLE
create table if not exists public.suppliers (
  id bigint generated by default as identity primary key,
  company_name varchar(255) not null,
  contact_name varchar(255),
  phone varchar(30),
  email varchar(100),
  address text,
  created_at timestamptz not null default now()
);

-- 12. PURCHASES TABLE
create table if not exists public.purchases (
  id bigint generated by default as identity primary key,
  supplier_id bigint references public.suppliers(id),
  total integer not null default 0,
  created_at timestamptz not null default now()
);

-- 13. PURCHASE_ITEMS TABLE
create table if not exists public.purchase_items (
  id bigint generated by default as identity primary key,
  purchase_id bigint references public.purchases(id) on delete cascade,
  product_id bigint references public.products(id),
  quantity integer not null,
  unit_cost integer not null,
  subtotal integer not null
);

-- 14. PRODUCT_IMAGES TABLE
create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete cascade,
  image_url text not null,
  created_at timestamptz not null default now()
);

-- ================================================================
-- TRANSACTIONAL RPC FUNCTION FOR PLACING AN ORDER
-- ================================================================
-- This function inserts the order, order_items, reduces stock,
-- and inserts records into inventory_movements inside one transaction.

create or replace function public.place_order_v2(
  p_customer_id bigint,
  p_subtotal integer,
  p_discount_amount integer,
  p_tax_amount integer,
  p_total integer,
  p_promo_code varchar,
  p_payment_method varchar,
  p_items jsonb -- Array of {product_id, quantity, unit_price, subtotal}
)
returns public.orders as $$
declare
  v_order public.orders;
  v_item jsonb;
  v_curr_stock integer;
  v_new_stock integer;
begin
  -- 1. Insert Order
  insert into public.orders (
    customer_id, subtotal, discount_amount, tax_amount, total, promo_code, payment_method, status
  ) values (
    p_customer_id, p_subtotal, p_discount_amount, p_tax_amount, p_total, p_promo_code, p_payment_method, 'Completado'
  )
  returning * into v_order;

  -- 2. Loop and Insert items & update stock
  for v_item in select * from jsonb_array_elements(p_items) loop
    -- Insert order item
    insert into public.order_items (
      order_id, product_id, quantity, unit_price, subtotal
    ) values (
      v_order.id, 
      (v_item->>'product_id')::bigint, 
      (v_item->>'quantity')::integer, 
      (v_item->>'unit_price')::integer, 
      (v_item->>'subtotal')::integer
    );

    -- Get current stock
    select stock into v_curr_stock 
    from public.products 
    where id = (v_item->>'product_id')::bigint;

    v_new_stock := v_curr_stock - (v_item->>'quantity')::integer;

    if v_new_stock < 0 then
      raise exception 'Stock insuficiente para el producto ID %', (v_item->>'product_id')::bigint;
    end if;

    -- Update stock in products
    update public.products
    set stock = v_new_stock
    where id = (v_item->>'product_id')::bigint;

    -- Register inventory movement
    insert into public.inventory_movements (
      product_id, movement_type, quantity, previous_stock, now_stock, notes
    ) values (
      (v_item->>'product_id')::bigint,
      'VENTA',
      (v_item->>'quantity')::integer,
      v_curr_stock,
      v_new_stock,
      'Venta realizada. Pedido #' || v_order.id
    );

  end loop;

  return v_order;
end;
$$ language plpgsql security definer;

-- ================================================================
-- ROW LEVEL SECURITY (RLS) - PUBLIC ACCESS BY DEFAULT FOR MOBILE
-- ================================================================

alter table public.customers enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.carts enable row level security;
alter table public.cart_items enable row level security;
alter table public.inventory_movements enable row level security;
alter table public.promotions enable row level security;
alter table public.users enable row level security;
alter table public.settings enable row level security;
alter table public.suppliers enable row level security;
alter table public.purchases enable row level security;
alter table public.purchase_items enable row level security;
alter table public.product_images enable row level security;

create policy "Public Customers Access" on public.customers for all using (true) with check (true);
create policy "Public Products Access" on public.products for all using (true) with check (true);
create policy "Public Orders Access" on public.orders for all using (true) with check (true);
create policy "Public Order Items Access" on public.order_items for all using (true) with check (true);
create policy "Public Carts Access" on public.carts for all using (true) with check (true);
create policy "Public Cart Items Access" on public.cart_items for all using (true) with check (true);
create policy "Public Inventory Access" on public.inventory_movements for all using (true) with check (true);
create policy "Public Promotions Access" on public.promotions for all using (true) with check (true);
create policy "Public Users Access" on public.users for all using (true) with check (true);
create policy "Public Settings Access" on public.settings for all using (true) with check (true);
create policy "Public Suppliers Access" on public.suppliers for all using (true) with check (true);
create policy "Public Purchases Access" on public.purchases for all using (true) with check (true);
create policy "Public Purchase Items Access" on public.purchase_items for all using (true) with check (true);
create policy "Public Product Images Access" on public.product_images for all using (true) with check (true);

-- ================================================================
-- SEED DEFAULT GUEST CUSTOMER
-- ================================================================
insert into public.customers (id, first_name, last_name, document_number, phone, email, address, city)
values (1, 'Cliente', 'General', '123456789', '555-5555', 'cliente@general.com', 'Tienda', 'Ciudad')
on conflict (id) do nothing;
