// src/constants/theme.js
export const COLORS = {
  // Background layers
  bgPrimary: '#0a0a0c',
  bgSecondary: '#121216',
  bgTertiary: '#1a1a22',
  bgCard: '#1e1e28',

  // Gold Accent
  gold: '#e5b83b',
  goldLight: '#fcd567',
  goldDark: '#c9971e',
  goldSoft: 'rgba(229,184,59,0.12)',

  // Status Colors
  success: '#2ecc71',
  successSoft: 'rgba(46,204,113,0.12)',
  danger: '#ff4d4d',
  dangerSoft: 'rgba(255,77,77,0.12)',
  info: '#3498db',
  infoSoft: 'rgba(52,152,219,0.12)',
  purple: '#9b59b6',
  purpleSoft: 'rgba(155,89,182,0.12)',

  // Text
  textPrimary: '#ffffff',
  textSecondary: '#a0a0ab',
  textMuted: '#6f6f79',
  textInverted: '#0a0a0c',

  // Borders
  border: 'rgba(255,255,255,0.08)',
  borderLight: 'rgba(255,255,255,0.15)',
};

export const FONTS = {
  light: '300',
  regular: '400',
  medium: '500',
  semibold: '600',
  bold: '700',
};

export const SIZES = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
  
  radiusSm: 8,
  radiusMd: 14,
  radiusLg: 24,
  radiusFull: 999,
};

// Category module config
export const CATEGORIES = [
  {
    id: 'all',
    label: 'Todo',
    icon: 'apps',
    color: COLORS.gold,
    gradient: ['#e5b83b', '#c9971e'],
  },
  {
    id: 'cerveza-nacional',
    label: 'Cervezas Nacionales',
    icon: 'beer',
    color: '#e5b83b',
    gradient: ['#f6d365', '#fda085'],
  },
  {
    id: 'cerveza-importada',
    label: 'Importadas',
    icon: 'beer-outline',
    color: '#3498db',
    gradient: ['#89f7fe', '#3498db'],
  },
  {
    id: 'licores',
    label: 'Licores',
    icon: 'wine',
    color: '#9b59b6',
    gradient: ['#c471f5', '#fa71cd'],
  },
  {
    id: 'snacks',
    label: 'Snacks',
    icon: 'fast-food',
    color: '#2ecc71',
    gradient: ['#11998e', '#38ef7d'],
  },
];

export const CATEGORY_LABELS = {
  'cerveza-nacional': 'Cerveza Nacional',
  'cerveza-importada': 'Cerveza Importada',
  'licores': 'Licor Fino',
  'snacks': 'Snack & Paquete',
};

export const INITIAL_PRODUCTS = [
  // Cervezas Nacionales
  {
    name: 'Club Colombia Dorada',
    category: 'cerveza-nacional',
    type: 'Rubia Lager Premium',
    price: 5200,
    stock: 48,
    image_url: 'https://images.unsplash.com/photo-1584225065152-4a1454aa3d4e?auto=format&fit=crop&w=500&q=80',
    description: 'Cerveza tipo lager premium nacional. Color dorado brillante, aroma maltoso y cuerpo balanceado.',
    featured: true,
  },
  {
    name: 'Águila Light',
    category: 'cerveza-nacional',
    type: 'Light Lager',
    price: 4500,
    stock: 72,
    image_url: 'https://images.unsplash.com/photo-1618885472179-5e474019f2a9?auto=format&fit=crop&w=500&q=80',
    description: 'Sabor suave y refrescante con bajo contenido de calorías. Ideal para climas cálidos.',
    featured: false,
  },
  {
    name: 'Cerveza Poker',
    category: 'cerveza-nacional',
    type: 'Lager Tradicional',
    price: 4200,
    stock: 60,
    image_url: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&w=500&q=80',
    description: 'La cerveza de los amigos. Lager tradicional con el amargor perfecto.',
    featured: false,
  },
  {
    name: 'Tres Cordilleras Rosada',
    category: 'cerveza-nacional',
    type: 'Craft Rosé Ale',
    price: 9800,
    stock: 24,
    image_url: 'https://images.unsplash.com/photo-1532634896-26909d0d7ebe?auto=format&fit=crop&w=500&q=80',
    description: 'Cerveza artesanal de Medellín. Notas frutales y fresas, fermentación especial.',
    featured: true,
  },
  // Cervezas Importadas
  {
    name: 'Corona Extra',
    category: 'cerveza-importada',
    type: 'Lager Mexicana',
    price: 7800,
    stock: 96,
    image_url: 'https://images.unsplash.com/photo-1600788886242-5c96aabe3757?auto=format&fit=crop&w=500&q=80',
    description: 'Cerveza premium de México. Perfecta bien fría con rodaja de limón.',
    featured: true,
  },
  {
    name: 'Heineken',
    category: 'cerveza-importada',
    type: 'Pale Lager Holandesa',
    price: 7200,
    stock: 120,
    image_url: 'https://images.unsplash.com/photo-1597075687490-8f673c6c17f6?auto=format&fit=crop&w=500&q=80',
    description: 'Cerveza holandesa con sabor distintivo y amargor refrescante de fama mundial.',
    featured: false,
  },
  {
    name: 'Stella Artois',
    category: 'cerveza-importada',
    type: 'Pilsner Belga',
    price: 8200,
    stock: 36,
    image_url: 'https://images.unsplash.com/photo-1598555772379-307f59d57a5b?auto=format&fit=crop&w=500&q=80',
    description: 'Pilsner belga de aroma floral, sabor lupulado y final limpio.',
    featured: false,
  },
  {
    name: 'Budweiser',
    category: 'cerveza-importada',
    type: 'American Lager',
    price: 6900,
    stock: 80,
    image_url: 'https://images.unsplash.com/photo-1555658636-6e4a36218be7?auto=format&fit=crop&w=500&q=80',
    description: 'La cerveza americana más famosa del mundo. Suave y refrescante.',
    featured: false,
  },
  // Licores
  {
    name: 'Johnnie Walker Black Label',
    category: 'licores',
    type: 'Whisky Escocés 12 Años',
    price: 165000,
    stock: 18,
    image_url: 'https://images.unsplash.com/photo-1527061011665-3652c757a4d4?auto=format&fit=crop&w=500&q=80',
    description: 'Whisky escocés blend premium añejado 12 años. Rico perfil ahumado e intenso.',
    featured: true,
  },
  {
    name: 'Ron Viejo de Caldas 8 Años',
    category: 'licores',
    type: 'Ron Añejo Colombiano',
    price: 78000,
    stock: 24,
    image_url: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=500&q=80',
    description: 'Ron colombiano añejado en barriles de roble blanco americano. Aroma dulce y maderas.',
    featured: true,
  },
  {
    name: 'Aguardiente Antioqueño Sin Azúcar',
    category: 'licores',
    type: 'Aguardiente',
    price: 54000,
    stock: 40,
    image_url: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=500&q=80',
    description: 'Licor tradicional anisado colombiano. Alcohol extrapuro y notas anisadas naturales.',
    featured: false,
  },
  {
    name: 'Old Parr 12 Años',
    category: 'licores',
    type: 'Whisky Escocés',
    price: 155000,
    stock: 15,
    image_url: 'https://images.unsplash.com/photo-1582819509237-d5b75f20ff7c?auto=format&fit=crop&w=500&q=80',
    description: 'Elegante escocés de gran suavidad con notas frutales, caramelo y ligero toque herbal.',
    featured: false,
  },
  {
    name: 'Tequila Don Julio Blanco',
    category: 'licores',
    type: 'Tequila 100% Agave',
    price: 215000,
    stock: 10,
    image_url: 'https://images.unsplash.com/photo-1516535794938-6063878f28cc?auto=format&fit=crop&w=500&q=80',
    description: 'Tequila premium ultra-suave de ágave azul. Notas cítricas e ideal para Margaritas.',
    featured: true,
  },
  {
    name: 'Baileys Irish Cream',
    category: 'licores',
    type: 'Licor de Crema',
    price: 85000,
    stock: 20,
    image_url: 'https://images.unsplash.com/photo-1585694861853-c40a59a22ca5?auto=format&fit=crop&w=500&q=80',
    description: 'El irresistible licor irlandés de crema con whisky y chocolate. Perfecto sobre hielo.',
    featured: false,
  },
  // Snacks
  {
    name: 'Papas Margarita Pollo',
    category: 'snacks',
    type: 'Papas Fritas',
    price: 5500,
    stock: 50,
    image_url: 'https://images.unsplash.com/photo-1566478989037-eec170784d20?auto=format&fit=crop&w=500&q=80',
    description: 'Crujientes papas fritas con el inconfundible sabor a pollo favorito en Colombia.',
    featured: false,
  },
  {
    name: 'Doritos Mega Queso',
    category: 'snacks',
    type: 'Tortillas de Maíz',
    price: 4900,
    stock: 45,
    image_url: 'https://images.unsplash.com/photo-1600952841320-db92ec4047ca?auto=format&fit=crop&w=500&q=80',
    description: 'Hojuelas de maíz con intenso sabor a queso Cheddar. El snack perfecto para cervezas.',
    featured: false,
  },
  {
    name: 'Mix Todorico',
    category: 'snacks',
    type: 'Mix de Snacks',
    price: 3800,
    stock: 35,
    image_url: 'https://images.unsplash.com/photo-1599490659273-e3b6942d68bb?auto=format&fit=crop&w=500&q=80',
    description: 'Mezcla de plátano maduro, chicharrón y papas fritas en un solo paquete.',
    featured: false,
  },
  {
    name: 'Maní Moto Picante',
    category: 'snacks',
    type: 'Maní Recubierto',
    price: 2900,
    stock: 80,
    image_url: 'https://images.unsplash.com/photo-1534119396591-5998e1578579?auto=format&fit=crop&w=500&q=80',
    description: 'Maní crujiente recubierto con cubierta tostada y salada con toque picante.',
    featured: false,
  },
];
